swagger: "2.0"
info:
  title: Sample API
  description: API description in Markdown.
  version: 1.0.0
basePath: /
schemes:
  - https
  - http
paths:
  /test:
    get:
      summmary: Test endpoint
      description: Test the endpoint
      responses:
        '200':
          description: JSON message
          content:
            applicaiton/json:
              schema:
                type: string