version: "3"
services:
  frontend:
    restart: always
    container_name: frontend
    image: mahew/pwa-frontend:latest
    ports:
      - 80:80
      - 443:443
    volumes:
      - /home/ubuntu/ssl:/etc/nginx/certs

  backend:
    restart: always
    container_name: backend
    image: mahew/pwa:latest
    expose:
      - 5000
    volumes:
      - ./backend:/usr/src/app
    environment:
      - FLASK_ENV=development
      - FLASK_APP=api.py
      - FLASK_DEBUG=1
      - DB_USERNAME=mastermonkey
      - DB_PASSWORD=9PPHJJdMjs5vvkU
      - DB_NAME=MonkeyDB
      - DB_URL=pwa-db.cgrwyltiiuin.us-east-2.rds.amazonaws.com
      - DEFAULT_ACCOUNT_USERNAME=admin
      - DEFAULT_ACCOUNT_PASSWORD=MasterMonkey
      - DEFAULT_ACCOUNT_ROLE=admin
