swagger: "2.0"
info:
  title: Sample API
  description: API description in Markdown.
  version: 1.0.0
basePath: /
schemes:
  - http
paths:
  /api/login:
    post:
      summary: Authenticates user and returns Bearer login token
      operationId: "Login"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        required: true
        schema:
          $ref: "#/definitions/auth"
      responses:
        "200":
            schema:
                $ref: "#/definitions/auth_token"
        "401":
            description: "Incorrect username or password"
            schema:
                $ref: "#/definitions/auth_wrong_password"
  /api/pickups:
    get:
      summary: Returns list of medical pickups
      operationId: getPickups
      produces:
      - "application/json"
      responses:
        "200":
            schema:
                $ref: "#/definitions/pickupList"
                        
definitions:
    auth:
        type: "object"
        properties:
            username:
                type: "string"
                example: "admin"
            password: 
                type: "string"
                example: "password"

    auth_token:
        type: "object"
        properties:
            access_token:
                type: "string"
                example: "Generated access token"
                
    auth_wrong_password:
        type: "object"
        properties:
            error:
                type: "string"
                example: "AuthenticationError"
            message:
                type: "string"
                example: "The username and/or password are incorrect"
            status_code:
                type: "integer"
                example: 401

    pickupList:
        type: "object"
        properties:
          pickup_id:
            type: "string"
            example: "UUId of pickup"
          drug_quantity:
            type: "integer"
            example: 3
          scheduled_date:
            type: "date"
            example: "2021-01-26"
          review_date:
            type: "date"
            example: "2021-01-26"
          authorisation_status:
            type: "string"
            example: "authorised"
          pickup_status:
            type: "string"
            example: "AWAITING_PICKUP"